apiVersion: v1
kind: Secret
metadata:
  name: evalhub-db-credentials
type: Opaque
stringData:
  db-url: "postgres://rhoai:dontdothisinprod@evalhubdb.redhat-ods-applications.svc.cluster.local:5432/evalhub"
