apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: evalhubdata
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10G
  storageClassName: gp3-csi
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: evalhubdb
  name: evalhubdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evalhubdb
  template:
    metadata:
      labels:
        app: evalhubdb
    spec:
      containers:
      - env:
        - name: POSTGRESQL_USER
          value: rhoai
        - name: POSTGRESQL_PASSWORD
          value: dontdothisinprod
        - name: POSTGRESQL_DATABASE
          value: evalhub
        image: registry.redhat.io/rhel9/postgresql-18
        imagePullPolicy: Always
        name: postgresql-18
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/pgsql/data
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: evalhubdata
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: evalhubdb
  name: evalhubdb
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: evalhubdb
  type: ClusterIP
